export const FETCH_LIST_FULFILL = "FETCH_LIST_FULFILL"
export const FETCH_LIST_PENDING = "FETCH_LIST_PENDING"
export const FETCH_LIST_REJECT = "FETCH_LIST_REJECT"
export const CLEAN_ERRMSG_LIST = "CLEAN_ERRMSG_LIST"